nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: "S\xE9bastien Guizard (@sguizard)"
  description: Genes and transcripts annotation with Isoseq using uLTRA and TAMA
  force: false
  is_nfcore: true
  name: isoseq
  org: nf-core
  outdir: .
  version: 2.1.0dev
